### ISSUE TITLE
PlatformIO works with lvgl@^8.3.4 & TFT_eSPI@^2.5.23

### ISSUE THREAD

**Issue by mtnrbq** [teastainGit/LilyGO-T-display-S3-setup-and-examples#5]
Thanks for the detailed setup notes and instructions - enabled me to get it working with latest libraries on platformIO

For anyone else using platformIO, the following platform.ini works with hothead
```
;platformio.ini
[env:lilygo-t-display-s3]
lib_ldf_mode=deep
platform = espressif32
board = lilygo-t-display-s3
framework = arduino
lib_deps = 
	lvgl/lvgl@^8.3.4
	bodmer/TFT_eSPI@^2.5.23

build_flags =
  ;###############################################################
  ; TFT_eSPI library setting here (no need to edit library files):
  ;###############################################################
  -D USER_SETUP_LOADED=1                        ; Set this settings as valid
  -include $PROJECT_LIBDEPS_DIR/$PIOENV/TFT_eSPI/User_Setups/Setup206_LilyGo_T_Display_S3.h
  -D LV_CONF_INCLUDE_SIMPLE
```
N.B. you need to copy the ```lv_conf.h``` file from the T-Display-S3 project @ ```...\lib\lvgl\lv_conf.h``` into your ```include``` folder
(or it could be included in this repo)

Hope this is of help to someone.

**Comment by teastainGit** [comment]
Thank you! 
I struggled with the LilyGO T-Display S3 at first so I put my thoughts into a repository.
Thanks for your PIO advice.
-Terry

**Comment by ktecho** [comment]
@mtnrbq Have you succesfully used lvgl with that setup? I'm able to see this app that uses TFT_eSPI, but I would like to use lvgl... Thanks!

**Comment by teastainGit** [comment]
Luis!I wrote those little apps to help get folks started on esp32s3!The LilyGO website has an LVGL example.To use this example, you have to download LilyGO’s entire LVGL library and overwrite your own existing LVGL library..LVGL is difficult to use because of the setup requirement.Try youtube Volos Projects for more info.Cheers !TerryOn Mar 2, 2025, at 5:18 AM, Luis Miguel ***@***.***> wrote:﻿
  @mtnrbq Have you succesfully used lvgl with that setup? I'm able to see this app that uses TFT_eSPI, but I would like to use lvgl... Thanks!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>



ktecho left a comment (teastainGit/LilyGO-T-display-S3-setup-and-examples#5)
@mtnrbq Have you succesfully used lvgl with that setup? I'm able to see this app that uses TFT_eSPI, but I would like to use lvgl... Thanks!
